<?php

namespace Database\Seeders;

use App\Models\MasterBarang;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class MasterBarangSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['id' => '344', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 3020 Micro', 'tahun_peroleh' => Carbon::now()->setYear('2010')->format('Y-m-d H:i:s'), 'nomor_seri' => '6P72Y42'],
            ['id' => '345', 'jenis' => 'Printer', 'merk' => 'HP', 'tipe' => 'Laserjet 2055', 'tahun_peroleh' => Carbon::now()->setYear('2010')->format('Y-m-d H:i:s'), 'nomor_seri' => 'CNCJ407425'],
            ['id' => '346', 'jenis' => 'Laptop', 'merk' => 'LENOVO', 'tipe' => 'Thinkpad', 'tahun_peroleh' => Carbon::now()->setYear('2009')->format('Y-m-d H:i:s'), 'nomor_seri' => 'XHWGK'],
            ['id' => '347', 'jenis' => 'Laptop', 'merk' => 'LENOVO', 'tipe' => 'V330-14IKB', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => 'MP1DWLN7'],
            ['id' => '348', 'jenis' => 'Headset/Earphone', 'merk' => 'Vivan', 'tipe' => 'Sport Bluetooth', 'tahun_peroleh' => Carbon::now()->setYear('2020')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '349', 'jenis' => 'Printer', 'merk' => 'CANON', 'tipe' => 'MX537', 'tahun_peroleh' => Carbon::now()->setYear('2015')->format('Y-m-d H:i:s'), 'nomor_seri' => '010006761976'],
            ['id' => '350', 'jenis' => 'UPS', 'merk' => 'VEKTOR ABLEREX', 'tipe' => 'VESTA 625/625L', 'tahun_peroleh' => Carbon::now()->setYear('2013')->format('Y-m-d H:i:s'), 'nomor_seri' => 'MA311041990'],
            ['id' => '351', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 780', 'tahun_peroleh' => Carbon::now()->setYear('2016')->format('Y-m-d H:i:s'), 'nomor_seri' => 'G3BH32S'],
            ['id' => '352', 'jenis' => 'Tablet', 'merk' => 'Samsung', 'tipe' => 'Galaxy Tab S4', 'tahun_peroleh' => Carbon::now()->setYear('2016')->format('Y-m-d H:i:s'), 'nomor_seri' => 'SM-T835'],
            ['id' => '353', 'jenis' => 'PC', 'merk' => 'ASUS', 'tipe' => 'EEETOP.2013IUTIB041C', 'tahun_peroleh' => Carbon::now()->setYear('2014')->format('Y-m-d H:i:s'), 'nomor_seri' => 'E9PTBX003546'],
            ['id' => '354', 'jenis' => 'Laptop', 'merk' => 'ASUS', 'tipe' => 'Zenbook', 'tahun_peroleh' => Carbon::now()->setYear('2016')->format('Y-m-d H:i:s'), 'nomor_seri' => 'EDU7LCUU'],
            ['id' => '355', 'jenis' => 'Printer', 'merk' => 'CANON', 'tipe' => 'Image Class LBP7018C', 'tahun_peroleh' => Carbon::now()->setYear('2013')->format('Y-m-d H:i:s'), 'nomor_seri' => 'MJLA5033773'],
            ['id' => '356', 'jenis' => 'Headset/Earphone', 'merk' => 'VIVAN', 'tipe' => 'WIRELESS', 'tahun_peroleh' => Carbon::now()->setYear('2020')->format('Y-m-d H:i:s'), 'nomor_seri' => '306010211B'],
            ['id' => '357', 'jenis' => 'PC', 'merk' => 'LENOVO', 'tipe' => 'Think Centre M710t', 'tahun_peroleh' => Carbon::now()->setYear('2016')->format('Y-m-d H:i:s'), 'nomor_seri' => '71Y3517'],
            ['id' => '358', 'jenis' => 'Laptop', 'merk' => 'LENOVO', 'tipe' => 'Ideapad V330-14IKB', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => 'MP1DWLZD'],
            ['id' => '359', 'jenis' => 'Laptop', 'merk' => 'LENOVO', 'tipe' => 'ThinkPad T14 Gen 1', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'PF-2J7X4G'],
            ['id' => '360', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 3040 Micro', 'tahun_peroleh' => Carbon::now()->setYear('2016')->format('Y-m-d H:i:s'), 'nomor_seri' => '1QFL7C2'],
            ['id' => '361', 'jenis' => 'UPS', 'merk' => 'EATON', 'tipe' => 'NV 600 H', 'tahun_peroleh' => Carbon::now()->setYear('2011')->format('Y-m-d H:i:s'), 'nomor_seri' => '439901211'],
            ['id' => '362', 'jenis' => 'Laptop', 'merk' => 'HP', 'tipe' => 'Probook', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => '3100102002'],
            ['id' => '363', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 780', 'tahun_peroleh' => Carbon::now()->setYear('2011')->format('Y-m-d H:i:s'), 'nomor_seri' => 'GGMH32S'],
            ['id' => '364', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 780', 'tahun_peroleh' => Carbon::now()->setYear('2011')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '365', 'jenis' => 'PC', 'merk' => 'Lenovo', 'tipe' => 'ThinkCentre M720t', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => 'PC18JDEG'],
            ['id' => '366', 'jenis' => 'UPS', 'merk' => 'EMERSON', 'tipe' => 'PSA600-SOHO', 'tahun_peroleh' => Carbon::now()->setYear('2010')->format('Y-m-d H:i:s'), 'nomor_seri' => '24171400451SH'],
            ['id' => '367', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 780', 'tahun_peroleh' => Carbon::now()->setYear('0')->format('Y-m-d H:i:s'), 'nomor_seri' => 'C1BH32S'],
            ['id' => '368', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 780', 'tahun_peroleh' => Carbon::now()->setYear('0')->format('Y-m-d H:i:s'), 'nomor_seri' => '63BH32S'],
            ['id' => '369', 'jenis' => 'Laptop', 'merk' => 'ASUS', 'tipe' => 'VIVO BOOK A442U', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => 'J2N0CV08H163089'],
            ['id' => '370', 'jenis' => 'PC', 'merk' => 'Lenovo', 'tipe' => 'ThinkCentre M720t', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => 'PC18RHSO'],
            ['id' => '371', 'jenis' => 'UPS', 'merk' => 'APC', 'tipe' => 'Back-UPS 650', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => '9B1928A05741'],
            ['id' => '372', 'jenis' => 'PC', 'merk' => 'Lenovo', 'tipe' => 'ThinkCentre M720t', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => 'PC18RE05'],
            ['id' => '373', 'jenis' => 'UPS', 'merk' => 'EMERSON', 'tipe' => 'PSA600-SOHO', 'tahun_peroleh' => Carbon::now()->setYear('0')->format('Y-m-d H:i:s'), 'nomor_seri' => '24171407443SH'],
            ['id' => '374', 'jenis' => 'Scanner', 'merk' => 'Fujitsu', 'tipe' => 'FI-5950', 'tahun_peroleh' => Carbon::now()->setYear('0')->format('Y-m-d H:i:s'), 'nomor_seri' => 'AA2CC00034'],
            ['id' => '375', 'jenis' => 'Printer', 'merk' => 'HP', 'tipe' => 'Color LaserJet Managed MFP E7782', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => 'CNC1L8D05Z'],
            ['id' => '376', 'jenis' => 'PC', 'merk' => 'Lenovo', 'tipe' => 'ThinkCentre M720t', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => 'PC18QFKY'],
            ['id' => '377', 'jenis' => 'UPS', 'merk' => 'APC', 'tipe' => 'Back-UPS 650', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => '9B1928A05738'],
            ['id' => '378', 'jenis' => 'PC', 'merk' => 'LENOVO', 'tipe' => 'Think Centre M720t', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => 'PC18RME1'],
            ['id' => '379', 'jenis' => 'UPS', 'merk' => 'APC', 'tipe' => 'Back-UPS 650', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => '9B1928A05317'],
            ['id' => '380', 'jenis' => 'UPS', 'merk' => 'APC', 'tipe' => 'Back-UPS 650', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => '9B1928A05314'],
            ['id' => '381', 'jenis' => 'PC', 'merk' => 'LENOVO', 'tipe' => 'Think Centre M720t', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => 'PC18RLEB'],
            ['id' => '382', 'jenis' => 'UPS', 'merk' => 'APC', 'tipe' => 'Back-UPS 650', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => '9B1935A30334'],
            ['id' => '383', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 3010', 'tahun_peroleh' => Carbon::now()->setYear('2013')->format('Y-m-d H:i:s'), 'nomor_seri' => 'BD62G2S'],
            ['id' => '384', 'jenis' => 'PC', 'merk' => 'LENOVO', 'tipe' => 'Think Centre M720t', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => 'PC18RMDW'],
            ['id' => '385', 'jenis' => 'UPS', 'merk' => 'APC', 'tipe' => 'Back-UPS 650', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => '9B1935A26367'],
            ['id' => '386', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 3010', 'tahun_peroleh' => Carbon::now()->setYear('2013')->format('Y-m-d H:i:s'), 'nomor_seri' => '2NB2G2S'],
            ['id' => '387', 'jenis' => 'PC', 'merk' => 'HP', 'tipe' => 'ProDesk 400 G5 SFF', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => '1CZ83101DK'],
            ['id' => '388', 'jenis' => 'UPS', 'merk' => 'APC', 'tipe' => 'Back-UPS 650', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => '9B1809A01832'],
            ['id' => '389', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => '', 'tahun_peroleh' => Carbon::now()->setYear('0')->format('Y-m-d H:i:s'), 'nomor_seri' => 'R87NHFC'],
            ['id' => '390', 'jenis' => 'PC', 'merk' => 'HP', 'tipe' => 'ProDesk 400 G5 SFF', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => '1CZ83101DF'],
            ['id' => '391', 'jenis' => 'UPS', 'merk' => 'APC', 'tipe' => 'Back-UPS 650', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => '9B1935A24465'],
            ['id' => '392', 'jenis' => 'UPS', 'merk' => 'EATON', 'tipe' => 'Ellipse MAX 850', 'tahun_peroleh' => Carbon::now()->setYear('2010')->format('Y-m-d H:i:s'), 'nomor_seri' => 'ADJK5102E'],
            ['id' => '393', 'jenis' => 'PC', 'merk' => 'HP', 'tipe' => 'ProDesk 400 G5 SFF', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => '1CZ831019H'],
            ['id' => '394', 'jenis' => 'UPS', 'merk' => 'APC', 'tipe' => 'Back-UPS 650', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => '9B1935A26366'],
            ['id' => '395', 'jenis' => 'Rak', 'merk' => 'DELL', 'tipe' => 'Power Edge VRTX Chasis', 'tahun_peroleh' => Carbon::now()->setYear('2015')->format('Y-m-d H:i:s'), 'nomor_seri' => '67BL862'],
            ['id' => '396', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'OptiPlex 3020', 'tahun_peroleh' => Carbon::now()->setYear('2016')->format('Y-m-d H:i:s'), 'nomor_seri' => '26MZY42'],
            ['id' => '397', 'jenis' => 'UPS', 'merk' => 'EATON', 'tipe' => 'Ellipse MAX 850', 'tahun_peroleh' => Carbon::now()->setYear('2010')->format('Y-m-d H:i:s'), 'nomor_seri' => 'ADJK5103E'],
            ['id' => '398', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 780', 'tahun_peroleh' => Carbon::now()->setYear('0')->format('Y-m-d H:i:s'), 'nomor_seri' => 'B3BH32S'],
            ['id' => '399', 'jenis' => 'PC', 'merk' => 'Lenovo', 'tipe' => 'ThinkCentre M720t', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => 'PC18RMAP'],
            ['id' => '400', 'jenis' => 'UPS', 'merk' => 'EATON', 'tipe' => 'Ellipse MAX 850', 'tahun_peroleh' => Carbon::now()->setYear('2010')->format('Y-m-d H:i:s'), 'nomor_seri' => 'ADJK5103C'],
            ['id' => '401', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 780', 'tahun_peroleh' => Carbon::now()->setYear('0')->format('Y-m-d H:i:s'), 'nomor_seri' => 'FJMH32S'],
            ['id' => '402', 'jenis' => 'UPS', 'merk' => 'EMERSON', 'tipe' => 'PSA600-SOHO', 'tahun_peroleh' => Carbon::now()->setYear('0')->format('Y-m-d H:i:s'), 'nomor_seri' => '24171400450SH'],
            ['id' => '403', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 330', 'tahun_peroleh' => Carbon::now()->setYear('2008')->format('Y-m-d H:i:s'), 'nomor_seri' => 'BQHST1S'],
            ['id' => '404', 'jenis' => 'PC', 'merk' => 'Lenovo', 'tipe' => 'ThinkCentre M720t', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => 'PC18RL6T'],
            ['id' => '405', 'jenis' => 'Guillotine', 'merk' => 'EBA', 'tipe' => 'EBA 480EP', 'tahun_peroleh' => Carbon::now()->setYear('2009')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '406', 'jenis' => 'PC', 'merk' => 'Lenovo', 'tipe' => 'ThinkCentre M720t', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => 'PC18RER9'],
            ['id' => '407', 'jenis' => 'UPS', 'merk' => 'APC', 'tipe' => 'Back-UPS 650', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => '9B1928A05768'],
            ['id' => '409', 'jenis' => 'PC', 'merk' => 'LENOVO', 'tipe' => 'Think Centre M720t', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => 'PC18RFEV'],
            ['id' => '410', 'jenis' => 'PC', 'merk' => 'Lenovo', 'tipe' => 'ThinkCentre M720t', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => 'PC18JDES'],
            ['id' => '411', 'jenis' => 'UPS', 'merk' => 'APC', 'tipe' => 'Back-UPS 650', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => '9B1928A05767'],
            ['id' => '412', 'jenis' => 'PC', 'merk' => 'LENOVO', 'tipe' => 'Think Centre M720t', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => 'PC18RFL7'],
            ['id' => '413', 'jenis' => 'UPS', 'merk' => 'APC', 'tipe' => 'Back-UPS 650', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => '9B1935A30336'],
            ['id' => '414', 'jenis' => 'PC', 'merk' => 'ASUS', 'tipe' => 'Asus All in One PC', 'tahun_peroleh' => Carbon::now()->setYear('2014')->format('Y-m-d H:i:s'), 'nomor_seri' => 'E9PTBX003535'],
            ['id' => '415', 'jenis' => 'PC', 'merk' => 'LENOVO', 'tipe' => 'Think Centre M720t', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => 'PC18RMCS'],
            ['id' => '416', 'jenis' => 'UPS', 'merk' => 'APC', 'tipe' => 'Back-UPS 650', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => '9B1935A26369'],
            ['id' => '417', 'jenis' => 'UPS', 'merk' => 'Pulsar', 'tipe' => 'Pulsar 1500', 'tahun_peroleh' => Carbon::now()->setYear('0')->format('Y-m-d H:i:s'), 'nomor_seri' => '113H23008'],
            ['id' => '418', 'jenis' => 'PC', 'merk' => 'HP', 'tipe' => 'ProDesk 400 G5 SFF', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => '1CZ83101MR'],
            ['id' => '419', 'jenis' => 'UPS', 'merk' => 'EMERSON', 'tipe' => 'PSA600-SOHO', 'tahun_peroleh' => Carbon::now()->setYear('0')->format('Y-m-d H:i:s'), 'nomor_seri' => '241711400449SH'],
            ['id' => '420', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => '', 'tahun_peroleh' => Carbon::now()->setYear('0')->format('Y-m-d H:i:s'), 'nomor_seri' => 'R86ZXTX'],
            ['id' => '421', 'jenis' => 'UPS', 'merk' => 'APC', 'tipe' => 'Back-UPS 650', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => '9B1935A30335'],
            ['id' => '422', 'jenis' => 'Server', 'merk' => 'AXWAY', 'tipe' => '-', 'tahun_peroleh' => Carbon::now()->setYear('0')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '423', 'jenis' => 'PC', 'merk' => 'HP', 'tipe' => 'Prodesk 41 G5 SFF', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => '1CZ83100WK'],
            ['id' => '424', 'jenis' => 'PC', 'merk' => 'HP', 'tipe' => 'ProDesk 400 G5 SFF', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => '1CZ831015K'],
            ['id' => '425', 'jenis' => 'UPS', 'merk' => 'APC', 'tipe' => 'Back-UPS 650', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => '9B1928A05740'],
            ['id' => '426', 'jenis' => 'Server', 'merk' => 'DELL', 'tipe' => 'Power Edge M630 Blade Server', 'tahun_peroleh' => Carbon::now()->setYear('2015')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '427', 'jenis' => 'PC', 'merk' => 'HP', 'tipe' => 'ProDesk 400 G5 SFF', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => '1CZ83100VW'],
            ['id' => '428', 'jenis' => 'UPS', 'merk' => 'EATON', 'tipe' => 'Ellipse MAX 850', 'tahun_peroleh' => Carbon::now()->setYear('2010')->format('Y-m-d H:i:s'), 'nomor_seri' => 'ADJK5103B'],
            ['id' => '429', 'jenis' => 'NAS', 'merk' => 'QNAP', 'tipe' => 'Xpension', 'tahun_peroleh' => Carbon::now()->setYear('0')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '430', 'jenis' => 'PC', 'merk' => 'Lenovo', 'tipe' => 'ThinkCentre M720t', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => 'PC180FOP'],
            ['id' => '431', 'jenis' => 'UPS', 'merk' => 'EMERSON', 'tipe' => 'PSA600-SOHO', 'tahun_peroleh' => Carbon::now()->setYear('0')->format('Y-m-d H:i:s'), 'nomor_seri' => '24171407094SH'],
            ['id' => '432', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 780', 'tahun_peroleh' => Carbon::now()->setYear('0')->format('Y-m-d H:i:s'), 'nomor_seri' => 'C5BH32S'],
            ['id' => '433', 'jenis' => 'Headset/Earphone', 'merk' => 'VIVAN', 'tipe' => 'WIRELESS', 'tahun_peroleh' => Carbon::now()->setYear('2020')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '434', 'jenis' => 'PC', 'merk' => 'Lenovo', 'tipe' => 'ThinkCentre M720t', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => 'PC18JPFO'],
            ['id' => '435', 'jenis' => 'UPS', 'merk' => 'EMERSON', 'tipe' => 'PSA600-SOHO', 'tahun_peroleh' => Carbon::now()->setYear('0')->format('Y-m-d H:i:s'), 'nomor_seri' => '24171407041SH'],
            ['id' => '436', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 780', 'tahun_peroleh' => Carbon::now()->setYear('0')->format('Y-m-d H:i:s'), 'nomor_seri' => '91BH32S'],
            ['id' => '437', 'jenis' => 'UPS', 'merk' => 'EMERSON', 'tipe' => 'PSA600-SOHO', 'tahun_peroleh' => Carbon::now()->setYear('0')->format('Y-m-d H:i:s'), 'nomor_seri' => '24171407442SH'],
            ['id' => '438', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 3020 Micro', 'tahun_peroleh' => Carbon::now()->setYear('0')->format('Y-m-d H:i:s'), 'nomor_seri' => 'HQ7ZY42'],
            ['id' => '439', 'jenis' => 'Printer', 'merk' => 'HP', 'tipe' => 'Color LaserJet Managed MFP E7782', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => 'CNC1L8X896'],
            ['id' => '440', 'jenis' => 'PC', 'merk' => 'Lenovo', 'tipe' => 'ThinkCentre M720t', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => 'PC18RHN9'],
            ['id' => '441', 'jenis' => 'PC', 'merk' => 'Lenovo', 'tipe' => 'ThinkCentre M720t', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => 'PC18RMCY'],
            ['id' => '442', 'jenis' => 'UPS', 'merk' => 'APC', 'tipe' => 'Back-UPS 650', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => '9B1928A05769'],
            ['id' => '443', 'jenis' => 'PC', 'merk' => 'LENOVO', 'tipe' => 'Think Centre M720t', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => 'PC18RHJZ'],
            ['id' => '444', 'jenis' => 'PC', 'merk' => 'Lenovo', 'tipe' => 'ThinkCentre M720t', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => 'PC18RHKB'],
            ['id' => '445', 'jenis' => 'UPS', 'merk' => 'APC', 'tipe' => 'Back-UPS 650', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => '9B1928A05739'],
            ['id' => '446', 'jenis' => 'PC', 'merk' => 'LENOVO', 'tipe' => 'Think Centre M720t', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => 'PC18RME3'],
            ['id' => '447', 'jenis' => 'UPS', 'merk' => 'APC', 'tipe' => 'Back-UPS 650', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => '9B1928A05315'],
            ['id' => '448', 'jenis' => 'PC', 'merk' => 'Lenovo', 'tipe' => 'ThinkCenter M80', 'tahun_peroleh' => Carbon::now()->setYear('2013')->format('Y-m-d H:i:s'), 'nomor_seri' => '4NK2F2S'],
            ['id' => '449', 'jenis' => 'PC', 'merk' => 'HP', 'tipe' => 'ProDesk 400 G5 SFF', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => '1CZ831010H'],
            ['id' => '450', 'jenis' => 'UPS', 'merk' => 'APC', 'tipe' => 'Back-UPS 650', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => '9B1928A05316'],
            ['id' => '451', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 330', 'tahun_peroleh' => Carbon::now()->setYear('0')->format('Y-m-d H:i:s'), 'nomor_seri' => '5BDMT1S'],
            ['id' => '452', 'jenis' => 'PC', 'merk' => 'HP', 'tipe' => 'ProDesk 400 G5 SFF', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => '1CZ83101QB'],
            ['id' => '453', 'jenis' => 'UPS', 'merk' => 'APC', 'tipe' => 'Back-UPS 650', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => '9B1935A30337'],
            ['id' => '454', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Think Centre M80', 'tahun_peroleh' => Carbon::now()->setYear('2011')->format('Y-m-d H:i:s'), 'nomor_seri' => 'R87NHAY'],
            ['id' => '455', 'jenis' => 'UPS', 'merk' => 'APC', 'tipe' => 'Back-UPS 650', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => '9B1935A26368'],
            ['id' => '456', 'jenis' => 'Server', 'merk' => 'AXWAY', 'tipe' => '-', 'tahun_peroleh' => Carbon::now()->setYear('0')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '457', 'jenis' => 'PC', 'merk' => 'HP', 'tipe' => 'ProDesk 400 G5 SFF', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => '1CZ83100Z8'],
            ['id' => '458', 'jenis' => 'UPS', 'merk' => 'APC', 'tipe' => 'Back-UPS 650', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => '9B1938A05766'],
            ['id' => '459', 'jenis' => 'Server', 'merk' => 'DELL', 'tipe' => 'Power Edge M520 Blade Server', 'tahun_peroleh' => Carbon::now()->setYear('2015')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '460', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'OptiPlex 3040', 'tahun_peroleh' => Carbon::now()->setYear('2016')->format('Y-m-d H:i:s'), 'nomor_seri' => '1PLR7C2'],
            ['id' => '461', 'jenis' => 'UPS', 'merk' => 'EMERSON', 'tipe' => 'PSA600-SOHO', 'tahun_peroleh' => Carbon::now()->setYear('0')->format('Y-m-d H:i:s'), 'nomor_seri' => '24171407093SH'],
            ['id' => '462', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 780', 'tahun_peroleh' => Carbon::now()->setYear('0')->format('Y-m-d H:i:s'), 'nomor_seri' => 'FGMH32S'],
            ['id' => '463', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 780', 'tahun_peroleh' => Carbon::now()->setYear('2010')->format('Y-m-d H:i:s'), 'nomor_seri' => 'CN-0U417N-64180-9AU-1Z3U'],
            ['id' => '464', 'jenis' => 'Headset/Earphone', 'merk' => 'Lainnya', 'tipe' => 'Wireless', 'tahun_peroleh' => Carbon::now()->setYear('2020')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '465', 'jenis' => 'PC', 'merk' => 'LENOVO', 'tipe' => 'Think Centre M80', 'tahun_peroleh' => Carbon::now()->setYear('2010')->format('Y-m-d H:i:s'), 'nomor_seri' => 'R87EVLV'],
            ['id' => '466', 'jenis' => 'Printer', 'merk' => 'Canon', 'tipe' => 'LBP7110CW', 'tahun_peroleh' => Carbon::now()->setYear('2012')->format('Y-m-d H:i:s'), 'nomor_seri' => 'MNBA008451'],
            ['id' => '467', 'jenis' => 'Headset/Earphone', 'merk' => 'Vivan', 'tipe' => 'Sport X', 'tahun_peroleh' => Carbon::now()->setYear('2020')->format('Y-m-d H:i:s'), 'nomor_seri' => '68831/SDPPI/2020'],
            ['id' => '468', 'jenis' => 'Laptop', 'merk' => 'LENOVO', 'tipe' => 'V330-141KB', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => 'MP1DWK0C'],
            ['id' => '469', 'jenis' => 'PC', 'merk' => 'LENOVO', 'tipe' => 'Think Centre M80', 'tahun_peroleh' => Carbon::now()->setYear('2011')->format('Y-m-d H:i:s'), 'nomor_seri' => '11S0A47015ZVJ64109X0CV'],
            ['id' => '470', 'jenis' => 'Printer', 'merk' => 'Canon', 'tipe' => 'MX537', 'tahun_peroleh' => Carbon::now()->setYear('2014')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '471', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 3040 Micro', 'tahun_peroleh' => Carbon::now()->setYear('0')->format('Y-m-d H:i:s'), 'nomor_seri' => '3.10.01.02.001'],
            ['id' => '472', 'jenis' => 'Headset/Earphone', 'merk' => 'Vivan', 'tipe' => 'Sport X True Wireless Stereo Earbuds', 'tahun_peroleh' => Carbon::now()->setYear('2020')->format('Y-m-d H:i:s'), 'nomor_seri' => 'enggelin'],
            ['id' => '473', 'jenis' => 'PC', 'merk' => 'ASUS', 'tipe' => 'Asus All In One PC Series', 'tahun_peroleh' => Carbon::now()->setYear('2014')->format('Y-m-d H:i:s'), 'nomor_seri' => 'E9PTBX003489'],
            ['id' => '474', 'jenis' => 'UPS', 'merk' => 'Emerson', 'tipe' => 'PSA600-SOHO', 'tahun_peroleh' => Carbon::now()->setYear('2014')->format('Y-m-d H:i:s'), 'nomor_seri' => '241711400452SH'],
            ['id' => '475', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 3040 Micro', 'tahun_peroleh' => Carbon::now()->setYear('0')->format('Y-m-d H:i:s'), 'nomor_seri' => 'R86ZXNN'],
            ['id' => '476', 'jenis' => 'Laptop', 'merk' => 'LENOVO', 'tipe' => 'IDEAPAD 3 14ARE05', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'SNPK23KG4M'],
            ['id' => '477', 'jenis' => 'PC', 'merk' => 'LENOVO', 'tipe' => 'Think Centre M710t', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => '9314949D-32E5-4914-B196-E959101B04C8'],
            ['id' => '478', 'jenis' => 'UPS', 'merk' => 'APC', 'tipe' => 'Back-UPS 650', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => '8X650LI-MS'],
            ['id' => '479', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 780', 'tahun_peroleh' => Carbon::now()->setYear('2009')->format('Y-m-d H:i:s'), 'nomor_seri' => 'CN-0U417N-64180-9AJ-1PBM'],
            ['id' => '480', 'jenis' => 'Tablet', 'merk' => 'Fujitsu', 'tipe' => 'M532', 'tahun_peroleh' => Carbon::now()->setYear('2013')->format('Y-m-d H:i:s'), 'nomor_seri' => 'B1R3200441'],
            ['id' => '481', 'jenis' => 'UPS', 'merk' => 'EATON', 'tipe' => 'ELIPSE', 'tahun_peroleh' => Carbon::now()->setYear('2010')->format('Y-m-d H:i:s'), 'nomor_seri' => 'MX850'],
            ['id' => '482', 'jenis' => 'PC', 'merk' => 'LENOVO', 'tipe' => 'Think Centre M710t', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => 'PC0XZFT4'],
            ['id' => '483', 'jenis' => 'Printer', 'merk' => 'CANON', 'tipe' => 'IMAGECLASS LBP 7110CW', 'tahun_peroleh' => Carbon::now()->setYear('2017')->format('Y-m-d H:i:s'), 'nomor_seri' => 'MNBA008436'],
            ['id' => '484', 'jenis' => 'TV', 'merk' => 'LG', 'tipe' => 'LED55UN7300PTC', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => '010INLV0G960'],
            ['id' => '485', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 780', 'tahun_peroleh' => Carbon::now()->setYear('2006')->format('Y-m-d H:i:s'), 'nomor_seri' => '7687-OEM-0011903-00102'],
            ['id' => '486', 'jenis' => 'PC', 'merk' => 'LENOVO', 'tipe' => 'Think Centre M80', 'tahun_peroleh' => Carbon::now()->setYear('2006')->format('Y-m-d H:i:s'), 'nomor_seri' => 'R87EXRL'],
            ['id' => '487', 'jenis' => 'UPS', 'merk' => 'ELIPSE', 'tipe' => 'MAX 850', 'tahun_peroleh' => Carbon::now()->setYear('2010')->format('Y-m-d H:i:s'), 'nomor_seri' => 'MX850'],
            ['id' => '488', 'jenis' => 'Laptop', 'merk' => 'HP', 'tipe' => 'Probook 440 G5', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => '1MJ83AV'],
            ['id' => '489', 'jenis' => 'PC', 'merk' => 'LENOVO', 'tipe' => 'Think Centre M710t', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => 'PC0X2FTQ'],
            ['id' => '490', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 780', 'tahun_peroleh' => Carbon::now()->setYear('2006')->format('Y-m-d H:i:s'), 'nomor_seri' => '7687-OEM-0011903-00102'],
            ['id' => '491', 'jenis' => 'PC', 'merk' => 'LENOVO', 'tipe' => 'Lenovo All In One PC', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => 'MP1AEFSR'],
            ['id' => '492', 'jenis' => 'Headset/Earphone', 'merk' => 'Vivan', 'tipe' => 'Wireless', 'tahun_peroleh' => Carbon::now()->setYear('2020')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '493', 'jenis' => 'PC', 'merk' => 'LENOVO', 'tipe' => 'Think Centre M720t', 'tahun_peroleh' => Carbon::now()->setYear('2011')->format('Y-m-d H:i:s'), 'nomor_seri' => '00371-OEM-8992671-00437'],
            ['id' => '494', 'jenis' => 'Laptop', 'merk' => 'Fujitsu', 'tipe' => 'Lifebook T Series', 'tahun_peroleh' => Carbon::now()->setYear('2011')->format('Y-m-d H:i:s'), 'nomor_seri' => '00426-OEM-8992662-00009'],
            ['id' => '495', 'jenis' => 'Headset/Earphone', 'merk' => 'Vivan', 'tipe' => 'Wireless', 'tahun_peroleh' => Carbon::now()->setYear('2020')->format('Y-m-d H:i:s'), 'nomor_seri' => 'Tidak ada'],
            ['id' => '496', 'jenis' => 'Printer', 'merk' => 'Canon', 'tipe' => 'MX537', 'tahun_peroleh' => Carbon::now()->setYear('2014')->format('Y-m-d H:i:s'), 'nomor_seri' => 'Tidak ada'],
            ['id' => '497', 'jenis' => 'PC', 'merk' => 'LENOVO', 'tipe' => 'Lenovo All In One PC', 'tahun_peroleh' => Carbon::now()->setYear('2011')->format('Y-m-d H:i:s'), 'nomor_seri' => '054011700428701'],
            ['id' => '498', 'jenis' => 'Laptop', 'merk' => 'LENOVO', 'tipe' => '4236-SAD S/N PB-CKVE4 12/04', 'tahun_peroleh' => Carbon::now()->setYear('2013')->format('Y-m-d H:i:s'), 'nomor_seri' => '4236SAD'],
            ['id' => '499', 'jenis' => 'UPS', 'merk' => 'Eaton', 'tipe' => 'Ellipse MAX 850', 'tahun_peroleh' => Carbon::now()->setYear('2011')->format('Y-m-d H:i:s'), 'nomor_seri' => '0000'],
            ['id' => '500', 'jenis' => 'Printer', 'merk' => 'epson', 'tipe' => 'L 1800', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => '310020300397'],
            ['id' => '501', 'jenis' => 'PC', 'merk' => 'LENOVO', 'tipe' => 'Lenovo All In One PC', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => '310010200166'],
            ['id' => '502', 'jenis' => 'UPS', 'merk' => 'Eaton', 'tipe' => 'Elipse Max 850', 'tahun_peroleh' => Carbon::now()->setYear('2010')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '503', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 780', 'tahun_peroleh' => Carbon::now()->setYear('2010')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '504', 'jenis' => 'Printer', 'merk' => 'Canon', 'tipe' => 'MX537', 'tahun_peroleh' => Carbon::now()->setYear('2015')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '505', 'jenis' => 'Printer', 'merk' => 'Canon', 'tipe' => 'ImageClass LBP7018C', 'tahun_peroleh' => Carbon::now()->setYear('2015')->format('Y-m-d H:i:s'), 'nomor_seri' => 'MJLA5003373'],
            ['id' => '506', 'jenis' => 'Printer', 'merk' => 'HP', 'tipe' => 'Laser Jet P2055D', 'tahun_peroleh' => Carbon::now()->setYear('2011')->format('Y-m-d H:i:s'), 'nomor_seri' => 'CNCJ407430'],
            ['id' => '507', 'jenis' => 'Laptop', 'merk' => 'LENOVO', 'tipe' => 'Ideapad V330-14IKB', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => 'MP1DWLYL'],
            ['id' => '508', 'jenis' => 'Headset/Earphone', 'merk' => 'Vivan', 'tipe' => 'Wireless', 'tahun_peroleh' => Carbon::now()->setYear('2020')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '509', 'jenis' => 'PC', 'merk' => 'LENOVO', 'tipe' => 'Lenovo All In One PC', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => 'MP1ARK3P'],
            ['id' => '510', 'jenis' => 'Printer', 'merk' => 'HP', 'tipe' => 'Laser Jet Pro MFP M130a', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => 'VNFNB03800'],
            ['id' => '511', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 3010 DT', 'tahun_peroleh' => Carbon::now()->setYear('2013')->format('Y-m-d H:i:s'), 'nomor_seri' => '53C2G2S'],
            ['id' => '512', 'jenis' => 'Headset/Earphone', 'merk' => 'vivan', 'tipe' => 'bluetooth ver. 05', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '513', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 3010 DT', 'tahun_peroleh' => Carbon::now()->setYear('2020')->format('Y-m-d H:i:s'), 'nomor_seri' => '7PKZF2S'],
            ['id' => '514', 'jenis' => 'Printer', 'merk' => 'HP', 'tipe' => 'Laser Jet Pro MFP M130A', 'tahun_peroleh' => Carbon::now()->setYear('2020')->format('Y-m-d H:i:s'), 'nomor_seri' => 'VCN7G05699'],
            ['id' => '515', 'jenis' => 'Headset/Earphone', 'merk' => 'Vivan', 'tipe' => '-', 'tahun_peroleh' => Carbon::now()->setYear('2020')->format('Y-m-d H:i:s'), 'nomor_seri' => '09'],
            ['id' => '516', 'jenis' => 'Laptop', 'merk' => 'HP 548 G4', 'tipe' => '-', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => '5CG8482RJ4'],
            ['id' => '517', 'jenis' => 'Headset/Earphone', 'merk' => 'VIVAN', 'tipe' => 'SportX', 'tahun_peroleh' => Carbon::now()->setYear('2020')->format('Y-m-d H:i:s'), 'nomor_seri' => '3060102118(lutfi)'],
            ['id' => '518', 'jenis' => 'PC', 'merk' => 'LENOVO', 'tipe' => 'Think Centre M80', 'tahun_peroleh' => Carbon::now()->setYear('2011')->format('Y-m-d H:i:s'), 'nomor_seri' => 'VIDZ796'],
            ['id' => '519', 'jenis' => 'Laptop', 'merk' => 'LENOVO', 'tipe' => 'Ideapad V330-14IKB', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => 'MP1DWJZ5'],
            ['id' => '520', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 780', 'tahun_peroleh' => Carbon::now()->setYear('0')->format('Y-m-d H:i:s'), 'nomor_seri' => 'CN-OU417N-64180-9AU-1Z1U'],
            ['id' => '521', 'jenis' => 'UPS', 'merk' => 'ETN', 'tipe' => 'Ellipse MAX', 'tahun_peroleh' => Carbon::now()->setYear('2009')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '522', 'jenis' => 'Laptop', 'merk' => 'HP', 'tipe' => 'Probook 440 G5', 'tahun_peroleh' => Carbon::now()->setYear('2017')->format('Y-m-d H:i:s'), 'nomor_seri' => '5CD8327X6C'],
            ['id' => '523', 'jenis' => 'Printer', 'merk' => 'Canon', 'tipe' => 'Laser Printer LBP6230dn', 'tahun_peroleh' => Carbon::now()->setYear('2014')->format('Y-m-d H:i:s'), 'nomor_seri' => 'NCBA103294'],
            ['id' => '524', 'jenis' => 'Headset/Earphone', 'merk' => 'Vivan', 'tipe' => '-', 'tahun_peroleh' => Carbon::now()->setYear('2020')->format('Y-m-d H:i:s'), 'nomor_seri' => '3060102118'],
            ['id' => '525', 'jenis' => 'Harddisk Eksternal', 'merk' => 'Buffalo', 'tipe' => 'HD-PXTiTU2', 'tahun_peroleh' => Carbon::now()->setYear('2010')->format('Y-m-d H:i:s'), 'nomor_seri' => '75571105200663'],
            ['id' => '526', 'jenis' => 'PC', 'merk' => 'ASUS', 'tipe' => 'Asus All In One PC Series', 'tahun_peroleh' => Carbon::now()->setYear('2014')->format('Y-m-d H:i:s'), 'nomor_seri' => 'E9PTBX003483'],
            ['id' => '527', 'jenis' => 'Laptop', 'merk' => 'LENOVO', 'tipe' => 'V330-14IKB', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => 'MP1DAQ9R'],
            ['id' => '528', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 3010 DT', 'tahun_peroleh' => Carbon::now()->setYear('2013')->format('Y-m-d H:i:s'), 'nomor_seri' => '19021624004'],
            ['id' => '529', 'jenis' => 'Laptop', 'merk' => 'LENOVO', 'tipe' => 'V330-14KB', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => 'MP1DWLMZ'],
            ['id' => '530', 'jenis' => 'Headset/Earphone', 'merk' => 'Vivan', 'tipe' => 'Vivan', 'tahun_peroleh' => Carbon::now()->setYear('2020')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '531', 'jenis' => 'PC', 'merk' => 'Alcatroz', 'tipe' => 'Azzura Z3VX', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => '50D16197-84D6-4156-91A0-0794EDD8FACE'],
            ['id' => '532', 'jenis' => 'Printer', 'merk' => 'Fuji Xerox', 'tipe' => 'DocuPrintC3055', 'tahun_peroleh' => Carbon::now()->setYear('2011')->format('Y-m-d H:i:s'), 'nomor_seri' => '059K46569-32P'],
            ['id' => '533', 'jenis' => 'UPS', 'merk' => 'APC', 'tipe' => 'Back-UPS 650', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => 'BX650LI-MS'],
            ['id' => '534', 'jenis' => 'PC', 'merk' => 'HP', 'tipe' => 'Prodesk 41 G5 SFF', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => '1CZ83101DM'],
            ['id' => '535', 'jenis' => 'Laptop', 'merk' => 'ASUS', 'tipe' => 'Vivobook A442U', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '536', 'jenis' => 'UPS', 'merk' => 'EATON', 'tipe' => 'Ellipse Max 850', 'tahun_peroleh' => Carbon::now()->setYear('2016')->format('Y-m-d H:i:s'), 'nomor_seri' => 'ADJK51031'],
            ['id' => '537', 'jenis' => 'Laptop', 'merk' => 'LENOVO', 'tipe' => 'V330-14IKB', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => 'MP1DWLZ4'],
            ['id' => '538', 'jenis' => 'PC', 'merk' => 'LENOVO', 'tipe' => 'Lenovo All In One PC', 'tahun_peroleh' => Carbon::now()->setYear('2015')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '539', 'jenis' => 'Printer', 'merk' => 'Canon', 'tipe' => 'Imageclass LBP7110cw', 'tahun_peroleh' => Carbon::now()->setYear('2014')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '540', 'jenis' => 'Printer', 'merk' => 'Epson', 'tipe' => 'L5190 series', 'tahun_peroleh' => Carbon::now()->setYear('2020')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '541', 'jenis' => 'Headset/Earphone', 'merk' => 'Viva Audio', 'tipe' => 'sport X', 'tahun_peroleh' => Carbon::now()->setYear('2020')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '542', 'jenis' => 'Laptop', 'merk' => 'HP', 'tipe' => 'Probook 440 G5', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => 'SCD8327X91'],
            ['id' => '543', 'jenis' => 'PC', 'merk' => 'LENOVO', 'tipe' => 'Lenovo All In One PC', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => 'MP1ARP3K'],
            ['id' => '544', 'jenis' => 'Tablet', 'merk' => 'ACER', 'tipe' => 'ultrabook', 'tahun_peroleh' => Carbon::now()->setYear('2015')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '545', 'jenis' => 'UPS', 'merk' => 'APC', 'tipe' => '650', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '546', 'jenis' => 'Monitor', 'merk' => 'Dell', 'tipe' => '-', 'tahun_peroleh' => Carbon::now()->setYear('2010')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '547', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 780', 'tahun_peroleh' => Carbon::now()->setYear('2011')->format('Y-m-d H:i:s'), 'nomor_seri' => '29LG32S'],
            ['id' => '548', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 780', 'tahun_peroleh' => Carbon::now()->setYear('2010')->format('Y-m-d H:i:s'), 'nomor_seri' => '4SLH32S'],
            ['id' => '549', 'jenis' => 'UPS', 'merk' => 'EATON', 'tipe' => 'NV 600H', 'tahun_peroleh' => Carbon::now()->setYear('2011')->format('Y-m-d H:i:s'), 'nomor_seri' => '439701178'],
            ['id' => '550', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 3020 micro', 'tahun_peroleh' => Carbon::now()->setYear('2015')->format('Y-m-d H:i:s'), 'nomor_seri' => 'HQ7ZY42'],
            ['id' => '551', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 3010 DT', 'tahun_peroleh' => Carbon::now()->setYear('0')->format('Y-m-d H:i:s'), 'nomor_seri' => '3100102001'],
            ['id' => '552', 'jenis' => 'Laptop', 'merk' => 'ASUS', 'tipe' => 'Vivo Book', 'tahun_peroleh' => Carbon::now()->setYear('2020')->format('Y-m-d H:i:s'), 'nomor_seri' => 'L9N0CV21N90940E'],
            ['id' => '553', 'jenis' => 'Headset/Earphone', 'merk' => 'Vivan', 'tipe' => 'Wireless', 'tahun_peroleh' => Carbon::now()->setYear('2020')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '554', 'jenis' => 'Headset/Earphone', 'merk' => 'Vivan', 'tipe' => 'Vivan', 'tahun_peroleh' => Carbon::now()->setYear('2020')->format('Y-m-d H:i:s'), 'nomor_seri' => '0'],
            ['id' => '555', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 780', 'tahun_peroleh' => Carbon::now()->setYear('2010')->format('Y-m-d H:i:s'), 'nomor_seri' => '1SLH32S'],
            ['id' => '556', 'jenis' => 'Laptop', 'merk' => 'LENOVO', 'tipe' => 'V330-141KB', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => 'MP1DWK0P'],
            ['id' => '557', 'jenis' => 'UPS', 'merk' => 'Ellipse', 'tipe' => 'Max 850', 'tahun_peroleh' => Carbon::now()->setYear('2010')->format('Y-m-d H:i:s'), 'nomor_seri' => '0'],
            ['id' => '558', 'jenis' => 'UPS', 'merk' => 'EATON', 'tipe' => 'Ellipse Max 850', 'tahun_peroleh' => Carbon::now()->setYear('2014')->format('Y-m-d H:i:s'), 'nomor_seri' => 'ADJK51037'],
            ['id' => '559', 'jenis' => 'PC', 'merk' => 'HP', 'tipe' => 'Prodesk 41 G5 SFF', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => '1CZ83101FJ'],
            ['id' => '560', 'jenis' => 'Printer', 'merk' => 'EPSON', 'tipe' => 'WF-7711', 'tahun_peroleh' => Carbon::now()->setYear('0')->format('Y-m-d H:i:s'), 'nomor_seri' => 'X45X007630'],
            ['id' => '561', 'jenis' => 'Printer', 'merk' => 'HP', 'tipe' => 'Laser Jet P 2055D', 'tahun_peroleh' => Carbon::now()->setYear('0')->format('Y-m-d H:i:s'), 'nomor_seri' => 'CNCJ407273'],
            ['id' => '562', 'jenis' => 'Headset/Earphone', 'merk' => 'VIVAN', 'tipe' => 'WIRELESS', 'tahun_peroleh' => Carbon::now()->setYear('0')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '563', 'jenis' => 'Laptop', 'merk' => 'ACER', 'tipe' => 'TravelMate Spin P4', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'NXVP4SN003142019F72N00'],
            ['id' => '564', 'jenis' => 'PC', 'merk' => 'LENOVO', 'tipe' => 'Lenovo All In One PC', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => 'MP1ARH3T'],
            ['id' => '565', 'jenis' => 'Laptop', 'merk' => 'LENOVO', 'tipe' => 'V330 14ikB', 'tahun_peroleh' => Carbon::now()->setYear('0')->format('Y-m-d H:i:s'), 'nomor_seri' => 'MP1DWM0V'],
            ['id' => '566', 'jenis' => 'Harddisk Eksternal', 'merk' => 'Buffalo', 'tipe' => '1 TB', 'tahun_peroleh' => Carbon::now()->setYear('0')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '567', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 3010 DT', 'tahun_peroleh' => Carbon::now()->setYear('2015')->format('Y-m-d H:i:s'), 'nomor_seri' => '95KZF2S'],
            ['id' => '568', 'jenis' => 'Printer', 'merk' => 'Epson', 'tipe' => 'WF-7711', 'tahun_peroleh' => Carbon::now()->setYear('2020')->format('Y-m-d H:i:s'), 'nomor_seri' => 'X45X007683'],
            ['id' => '569', 'jenis' => 'Headset/Earphone', 'merk' => 'Vivan', 'tipe' => 'hitam', 'tahun_peroleh' => Carbon::now()->setYear('2020')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '570', 'jenis' => 'Laptop', 'merk' => 'LENOVO', 'tipe' => 'V330-14IKB', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => 'MP1DWKKW'],
            ['id' => '571', 'jenis' => 'UPS', 'merk' => 'MGE', 'tipe' => 'ELLIPSE MAX 850', 'tahun_peroleh' => Carbon::now()->setYear('0')->format('Y-m-d H:i:s'), 'nomor_seri' => 'ADJ71102P'],
            ['id' => '572', 'jenis' => 'Headset/Earphone', 'merk' => 'Vivan', 'tipe' => 'Sport x', 'tahun_peroleh' => Carbon::now()->setYear('2020')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '573', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 3010 DT', 'tahun_peroleh' => Carbon::now()->setYear('2013')->format('Y-m-d H:i:s'), 'nomor_seri' => 'CFKZF2S'],
            ['id' => '574', 'jenis' => 'Laptop', 'merk' => 'HP', 'tipe' => 'Probook 440 G5', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => 'SCD8327X93'],
            ['id' => '575', 'jenis' => 'PC', 'merk' => 'ASUS', 'tipe' => 'Asus All In One PC Series', 'tahun_peroleh' => Carbon::now()->setYear('2014')->format('Y-m-d H:i:s'), 'nomor_seri' => 'E9PTBX003513'],
            ['id' => '576', 'jenis' => 'Laptop', 'merk' => 'ACER', 'tipe' => 'Aspire P3', 'tahun_peroleh' => Carbon::now()->setYear('2017')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '577', 'jenis' => 'Printer', 'merk' => 'CANON', 'tipe' => 'Laser Printer LBP6230dn', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => 'NCBA103291'],
            ['id' => '578', 'jenis' => 'Headset/Earphone', 'merk' => 'VIVAN', 'tipe' => 'Wireless', 'tahun_peroleh' => Carbon::now()->setYear('2020')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '579', 'jenis' => 'Laptop', 'merk' => 'Acer', 'tipe' => 'Aspire P3', 'tahun_peroleh' => Carbon::now()->setYear('0')->format('Y-m-d H:i:s'), 'nomor_seri' => '000'],
            ['id' => '580', 'jenis' => 'PC', 'merk' => 'LENOVO', 'tipe' => 'Think Centre M80', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => '000'],
            ['id' => '581', 'jenis' => 'Printer', 'merk' => 'CANON', 'tipe' => 'LBP630', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '582', 'jenis' => 'Printer', 'merk' => 'HP Laserjet', 'tipe' => 'P2055D', 'tahun_peroleh' => Carbon::now()->setYear('2011')->format('Y-m-d H:i:s'), 'nomor_seri' => '054011700428701'],
            ['id' => '583', 'jenis' => 'UPS', 'merk' => 'Eaton', 'tipe' => 'NV 600 H', 'tahun_peroleh' => Carbon::now()->setYear('2011')->format('Y-m-d H:i:s'), 'nomor_seri' => '054011700428701000KD.2011'],
            ['id' => '584', 'jenis' => 'Scanner', 'merk' => 'Fujitsu', 'tipe' => 'fi-7260', 'tahun_peroleh' => Carbon::now()->setYear('2011')->format('Y-m-d H:i:s'), 'nomor_seri' => '000'],
            ['id' => '585', 'jenis' => 'PC', 'merk' => 'LENOVO', 'tipe' => 'Think Centre M710t', 'tahun_peroleh' => Carbon::now()->setYear('2011')->format('Y-m-d H:i:s'), 'nomor_seri' => '054011700428701'],
            ['id' => '586', 'jenis' => 'Laptop', 'merk' => 'LENOVO', 'tipe' => 'Thinkpad 4236-sad', 'tahun_peroleh' => Carbon::now()->setYear('2010')->format('Y-m-d H:i:s'), 'nomor_seri' => '000'],
            ['id' => '587', 'jenis' => 'UPS', 'merk' => 'ICA', 'tipe' => '000', 'tahun_peroleh' => Carbon::now()->setYear('2015')->format('Y-m-d H:i:s'), 'nomor_seri' => '054011700428701000KD.2015'],
            ['id' => '588', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 3040 Micro', 'tahun_peroleh' => Carbon::now()->setYear('2016')->format('Y-m-d H:i:s'), 'nomor_seri' => 'CN-OVCX8C-72872-621-CT1L-AOO'],
            ['id' => '589', 'jenis' => 'Headset/Earphone', 'merk' => 'Vivan', 'tipe' => 'Sport X', 'tahun_peroleh' => Carbon::now()->setYear('2020')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '590', 'jenis' => 'Harddisk Eksternal', 'merk' => 'Buffalo', 'tipe' => 'BUF-HD-HC500U2', 'tahun_peroleh' => Carbon::now()->setYear('2011')->format('Y-m-d H:i:s'), 'nomor_seri' => '45581080748684'],
            ['id' => '591', 'jenis' => 'Laptop', 'merk' => 'LENOVO', 'tipe' => 'Ideapad V330-14IKB', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => 'MP1DWLXS'],
            ['id' => '592', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 3040 Micro', 'tahun_peroleh' => Carbon::now()->setYear('2016')->format('Y-m-d H:i:s'), 'nomor_seri' => '44906449506'],
            ['id' => '593', 'jenis' => 'Laptop', 'merk' => 'Fujitsu', 'tipe' => 'LIFEBOOK T SERIES', 'tahun_peroleh' => Carbon::now()->setYear('2009')->format('Y-m-d H:i:s'), 'nomor_seri' => 'FPCO1187DK'],
            ['id' => '594', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 780', 'tahun_peroleh' => Carbon::now()->setYear('2011')->format('Y-m-d H:i:s'), 'nomor_seri' => '91BH325 19670780116'],
            ['id' => '595', 'jenis' => 'PC', 'merk' => 'LENOVO', 'tipe' => 'Lenovo All In One PC', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'MP1ARP3T'],
            ['id' => '596', 'jenis' => 'Laptop', 'merk' => 'ASUS', 'tipe' => 'Vivo Book 14', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'L9N0CV21N92540C'],
            ['id' => '597', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 3020 Micro', 'tahun_peroleh' => Carbon::now()->setYear('0')->format('Y-m-d H:i:s'), 'nomor_seri' => '00330-80000-00000-AA617'],
            ['id' => '598', 'jenis' => 'Laptop', 'merk' => 'HP', 'tipe' => 'HP 348 G8', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => '5C68482RJL'],
            ['id' => '599', 'jenis' => 'UPS', 'merk' => 'Vesta 625', 'tipe' => 'Vektor Ablerex', 'tahun_peroleh' => Carbon::now()->setYear('2017')->format('Y-m-d H:i:s'), 'nomor_seri' => 'MA 311041970'],
            ['id' => '600', 'jenis' => 'Harddisk Eksternal', 'merk' => 'Buffalo', 'tipe' => 'BUF-HD-PX500U2(B)', 'tahun_peroleh' => Carbon::now()->setYear('2011')->format('Y-m-d H:i:s'), 'nomor_seri' => '75570705124959'],
            ['id' => '601', 'jenis' => 'Laptop', 'merk' => 'ASUS', 'tipe' => 'ROG GL503G', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => 'J9NRCX04B30640D'],
            ['id' => '602', 'jenis' => 'UPS', 'merk' => 'EMERSON', 'tipe' => 'PSA600-SOHO', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => '241711407444SH'],
            ['id' => '603', 'jenis' => 'PC', 'merk' => 'HP', 'tipe' => 'Prodesk 41 G5 SFF', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => '1CZ83101P0'],
            ['id' => '604', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 780', 'tahun_peroleh' => Carbon::now()->setYear('2013')->format('Y-m-d H:i:s'), 'nomor_seri' => 'C5BH32S'],
            ['id' => '605', 'jenis' => 'UPS', 'merk' => 'Eaton', 'tipe' => 'NV 600H', 'tahun_peroleh' => Carbon::now()->setYear('2013')->format('Y-m-d H:i:s'), 'nomor_seri' => '439900577'],
            ['id' => '606', 'jenis' => 'Laptop', 'merk' => 'ASUS', 'tipe' => 'ROG Zephyrus G14', 'tahun_peroleh' => Carbon::now()->setYear('2020')->format('Y-m-d H:i:s'), 'nomor_seri' => 'L7NRKD00444030G'],
            ['id' => '607', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 3040 Micro', 'tahun_peroleh' => Carbon::now()->setYear('2016')->format('Y-m-d H:i:s'), 'nomor_seri' => 'CN-OVCX8C-72872-621-A1DL-AOO'],
            ['id' => '608', 'jenis' => 'Laptop', 'merk' => 'Acer', 'tipe' => 'Hibrid P3', 'tahun_peroleh' => Carbon::now()->setYear('2014')->format('Y-m-d H:i:s'), 'nomor_seri' => '5cd8327x7x'],
            ['id' => '609', 'jenis' => 'PC', 'merk' => 'LENOVO', 'tipe' => 'F0D4', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => 'MP1AEA4K'],
            ['id' => '610', 'jenis' => 'Headset/Earphone', 'merk' => 'Advance', 'tipe' => 'Lainnya', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'DWIR4H4RJO'],
            ['id' => '611', 'jenis' => 'Printer', 'merk' => 'HP Laser Jet ', 'tipe' => 'MFP M 130a', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => 'VNCNJ05546'],
            ['id' => '612', 'jenis' => 'Printer', 'merk' => 'HP Laser Jet P2055d', 'tipe' => 'P 2055D', 'tahun_peroleh' => Carbon::now()->setYear('2011')->format('Y-m-d H:i:s'), 'nomor_seri' => 'CNCJ407272'],
            ['id' => '613', 'jenis' => 'PC', 'merk' => 'LENOVO', 'tipe' => 'Think Centre M80', 'tahun_peroleh' => Carbon::now()->setYear('2011')->format('Y-m-d H:i:s'), 'nomor_seri' => 'v1dy976'],
            ['id' => '614', 'jenis' => 'Headset/Earphone', 'merk' => 'Advance', 'tipe' => 'Lainnya', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '615', 'jenis' => 'PC', 'merk' => 'ASUS', 'tipe' => 'Asus All In One PC Series', 'tahun_peroleh' => Carbon::now()->setYear('2014')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '616', 'jenis' => 'Printer', 'merk' => 'canon', 'tipe' => 'lbp6230dn', 'tahun_peroleh' => Carbon::now()->setYear('2014')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '617', 'jenis' => 'UPS', 'merk' => 'apc', 'tipe' => 'bx650li-ms', 'tahun_peroleh' => Carbon::now()->setYear('2015')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '618', 'jenis' => 'UPS', 'merk' => 'MGE', 'tipe' => 'ELLIPSE MAX 850', 'tahun_peroleh' => Carbon::now()->setYear('2008')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '619', 'jenis' => 'UPS', 'merk' => 'ETN', 'tipe' => 'Eaton NV 600', 'tahun_peroleh' => Carbon::now()->setYear('2010')->format('Y-m-d H:i:s'), 'nomor_seri' => '439901210'],
            ['id' => '620', 'jenis' => 'Printer', 'merk' => 'EPSON', 'tipe' => 'L6170', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '621', 'jenis' => 'Scanner', 'merk' => 'Epson', 'tipe' => 'Scanner Portabel Dokumen Warna WF-ES60W J421A 5V ', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'X5RH000591'],
            ['id' => '622', 'jenis' => 'PC', 'merk' => 'LENOVO', 'tipe' => 'IDEAPAD V330-14IKB', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '623', 'jenis' => 'PC', 'merk' => 'LENOVO', 'tipe' => 'Lenovo All In One PC', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => 'mp1arp36'],
            ['id' => '624', 'jenis' => 'Printer', 'merk' => 'epson', 'tipe' => 'l5190', 'tahun_peroleh' => Carbon::now()->setYear('2020')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '625', 'jenis' => 'Headset/Earphone', 'merk' => 'Advan', 'tipe' => '-', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '626', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 3020 Micro', 'tahun_peroleh' => Carbon::now()->setYear('2015')->format('Y-m-d H:i:s'), 'nomor_seri' => 'NCBA103297'],
            ['id' => '627', 'jenis' => 'Laptop', 'merk' => 'LENOVO', 'tipe' => 'ThinkPad T14 Gen 1', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'PF-2J7TWH'],
            ['id' => '628', 'jenis' => 'Printer', 'merk' => 'EPSON', 'tipe' => 'L6170', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'X4EZ01394'],
            ['id' => '629', 'jenis' => 'Laptop', 'merk' => 'ACER', 'tipe' => 'TravelMate Spin P4', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'NXP'],
            ['id' => '630', 'jenis' => 'Laptop', 'merk' => 'ACER', 'tipe' => 'TravelMate Spin P4', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => '142006658223'],
            ['id' => '631', 'jenis' => 'Laptop', 'merk' => 'ACER', 'tipe' => 'TravelMate Spin P4', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'NXVP4SN00314201A172N00'],
            ['id' => '632', 'jenis' => 'Laptop', 'merk' => 'Hp Probook 440 Gs', 'tipe' => 'probook 440 GS', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => '054011700428701000KD-2018'],
            ['id' => '633', 'jenis' => 'Laptop', 'merk' => 'HP', 'tipe' => 'Probook 440 G5', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => '5CD8327C60'],
            ['id' => '634', 'jenis' => 'Laptop', 'merk' => 'ACER', 'tipe' => 'TravelMate Spin P4', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'NXVP4SN003142019F82N00'],
            ['id' => '635', 'jenis' => 'Laptop', 'merk' => 'ACER', 'tipe' => 'TravelMate Spin P4', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'NXVP4SN00314201AOE2N00 (dwi)'],
            ['id' => '636', 'jenis' => 'Laptop', 'merk' => 'ACER', 'tipe' => 'TravelMate Spin P4', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'NXVP4SN00314201A002N00'],
            ['id' => '637', 'jenis' => 'Laptop', 'merk' => 'LENOVO', 'tipe' => 'V330-14IKB', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => 'MP1DWLZD'],
            ['id' => '638', 'jenis' => 'Laptop', 'merk' => 'ACER', 'tipe' => 'TravelMate Spin P4', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'NXVP4SN003142019F32N00'],
            ['id' => '639', 'jenis' => 'Laptop', 'merk' => 'ACER', 'tipe' => 'TravelMate Spin P4', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'N20H4'],
            ['id' => '640', 'jenis' => 'Laptop', 'merk' => 'Acer', 'tipe' => 'TravelMate Spin P4', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'NXVP4SN00314201A0A2N00'],
            ['id' => '641', 'jenis' => 'PC', 'merk' => 'ACER', 'tipe' => 'TravelMate Spin P4', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'NXPV4SN00314201A102N00'],
            ['id' => '642', 'jenis' => 'Laptop', 'merk' => 'ACER', 'tipe' => 'TravelMate Spin P4', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'NXVP4SN003142019C52N00'],
            ['id' => '643', 'jenis' => 'Laptop', 'merk' => 'ACER', 'tipe' => 'TravelMate Spin P4', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => '14200674223'],
            ['id' => '644', 'jenis' => 'Laptop', 'merk' => 'ACER', 'tipe' => 'TravelMate Spin P4', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => '-'],
            ['id' => '645', 'jenis' => 'Laptop', 'merk' => 'Acer ', 'tipe' => 'TravelMate Spin P4', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'NXVP4SN003142019B92N00'],
            ['id' => '646', 'jenis' => 'Laptop', 'merk' => 'LENOVO', 'tipe' => 'ThinkPad T14 Gen 1', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'PF-2J7X1E'],
            ['id' => '647', 'jenis' => 'Laptop', 'merk' => 'ACER', 'tipe' => 'TravelMate Spin P4', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'NXVP4SN003142019E32N00'],
            ['id' => '648', 'jenis' => 'Laptop', 'merk' => 'LENOVO', 'tipe' => 'V330', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => '3100102002'],
            ['id' => '649', 'jenis' => 'Laptop', 'merk' => 'ACER', 'tipe' => 'TravelMate Spin P4', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'NXVP4SN003142019D52N00'],
            ['id' => '650', 'jenis' => 'Laptop', 'merk' => 'ACER', 'tipe' => 'TravelMate P model N20H4', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'NXVP4SN003142019D52N00'],
            ['id' => '651', 'jenis' => 'Laptop', 'merk' => 'ACER', 'tipe' => 'TravelMate P model N20H4', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'NXVP4SN003142019D52N00'],
            ['id' => '652', 'jenis' => 'Laptop', 'merk' => 'LENOVO', 'tipe' => 'Lenovo V330-141KB', 'tahun_peroleh' => Carbon::now()->setYear('2000')->format('Y-m-d H:i:s'), 'nomor_seri' => 'MP2DWMOB'],
            ['id' => '653', 'jenis' => 'Laptop', 'merk' => 'Lenovo', 'tipe' => 'Lenovo V330-141KB', 'tahun_peroleh' => Carbon::now()->setYear('2000')->format('Y-m-d H:i:s'), 'nomor_seri' => 'MP1DWMOB'],
            ['id' => '654', 'jenis' => 'Laptop', 'merk' => 'ACER', 'tipe' => 'TravelMate Spin P4', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'NXVP4SN003142019CF2N00'],
            ['id' => '655', 'jenis' => 'Laptop', 'merk' => 'ACER', 'tipe' => 'TravelMate Spin P4', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'NXVP4SN003142019F22N00'],
            ['id' => '659', 'jenis' => 'Laptop', 'merk' => 'LENOVO', 'tipe' => 'Lenovo V330', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => 'MP1DALSH'],
            ['id' => '660', 'jenis' => 'Mouse', 'merk' => 'Logitech', 'tipe' => 'M170', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => '2053LZD0JT99'],
            ['id' => '661', 'jenis' => 'Laptop', 'merk' => 'ACER', 'tipe' => 'TravelMate Spin P4', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'NXVP4SN003142019C82N00'],
            ['id' => '662', 'jenis' => 'Laptop', 'merk' => 'ACER', 'tipe' => 'TravelMate Spin P4', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'NXVP4SN003142019D82N00'],
            ['id' => '663', 'jenis' => 'Laptop', 'merk' => 'ACER', 'tipe' => 'TravelMate Spin P4', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'NXVP4SN003142019DFN00'],
            ['id' => '664', 'jenis' => 'Laptop', 'merk' => 'ACER', 'tipe' => 'TravelMate Spin P4', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'NXVP4SN003142019DA2N00'],
            ['id' => '665', 'jenis' => 'Laptop', 'merk' => 'ACER', 'tipe' => 'TravelMate Spin P4', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'NXVP4SN003142019BF2N00'],
            ['id' => '666', 'jenis' => 'Laptop', 'merk' => 'ACER', 'tipe' => 'TravelMate Spin P4', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'NXVP4SN003142019D12N00'],
            ['id' => '667', 'jenis' => 'Laptop', 'merk' => 'ACER', 'tipe' => 'TravelMate Spin P4', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'NXVP4SN003142019DC2N00'],
            ['id' => '668', 'jenis' => 'Laptop', 'merk' => 'ACER', 'tipe' => 'TravelMate Spin P4', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'NXVP4SN003142019092N00'],
            ['id' => '669', 'jenis' => 'Laptop', 'merk' => 'ACER', 'tipe' => 'TravelMate Spin P4', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'NXVP4SN0031420199EB2N00TMP414RN-51-74AXM'],
            ['id' => '670', 'jenis' => 'Laptop', 'merk' => 'ACER', 'tipe' => 'TravelMate Spin P4', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'NXVP4SN00314201a072N00'],
            ['id' => '671', 'jenis' => 'Laptop', 'merk' => 'LENOVO', 'tipe' => 'V330-141KB', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'MP1DWMOV'],
            ['id' => '673', 'jenis' => 'Laptop', 'merk' => 'LENOVO', 'tipe' => 'ThinkPad T14 Gen 1', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'PF-2J7S4D'],
            ['id' => '674', 'jenis' => 'Laptop', 'merk' => 'ACER', 'tipe' => 'TravelMate Spin P4', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'NXVP4SN003142019D22N00'],
            ['id' => '675', 'jenis' => 'UPS', 'merk' => 'ICA', 'tipe' => 'CN1300', 'tahun_peroleh' => Carbon::now()->setYear('2000')->format('Y-m-d H:i:s'), 'nomor_seri' => '1J1HR1502089'],
            ['id' => '676', 'jenis' => 'Laptop', 'merk' => 'ACER', 'tipe' => 'TravelMate Spin P4', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'NXVP4SN003142019E22N00'],
            ['id' => '677', 'jenis' => 'Laptop', 'merk' => 'ASUS', 'tipe' => 'VIVO BOOK A442U', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => 'J2N0CV08H163089'],
            ['id' => '678', 'jenis' => 'Laptop', 'merk' => 'ASUS', 'tipe' => 'Notebook UX390U', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => 'J5N0CYKKR00L229'],
            ['id' => '679', 'jenis' => 'Laptop', 'merk' => 'LENOVO', 'tipe' => 'V330-14IKB', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => 'MP1DWLYL'],
            ['id' => '680', 'jenis' => 'Laptop', 'merk' => 'LENOVO', 'tipe' => 'Lainnya', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'MP1DWJZC'],
            ['id' => '681', 'jenis' => 'UPS', 'merk' => 'Vertiv Liebert', 'tipe' => 'PSA600-SOHO', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => '241711407096SH'],
            ['id' => '682', 'jenis' => 'Laptop', 'merk' => 'HP', 'tipe' => 'Probook 440 G5', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => '3.10.01.02.002'],
            ['id' => '683', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 3040 Micro', 'tahun_peroleh' => Carbon::now()->setYear('2013')->format('Y-m-d H:i:s'), 'nomor_seri' => '3.10.01.02.001'],
            ['id' => '684', 'jenis' => 'Headset/Earphone', 'merk' => 'Vivan', 'tipe' => 'sport x', 'tahun_peroleh' => Carbon::now()->setYear('2020')->format('Y-m-d H:i:s'), 'nomor_seri' => 'bhayu'],
            ['id' => '685', 'jenis' => 'Laptop', 'merk' => 'ASUS', 'tipe' => 'vivobook a442u', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => 'J2N0CV08H16208B'],
            ['id' => '687', 'jenis' => 'Laptop', 'merk' => 'LENOVO', 'tipe' => 'Lainnya', 'tahun_peroleh' => Carbon::now()->setYear('2012')->format('Y-m-d H:i:s'), 'nomor_seri' => 'PB-CKVE4 12/04'],
            ['id' => '688', 'jenis' => 'UPS', 'merk' => 'Ellipse Max', 'tipe' => '850 USBS IEC', 'tahun_peroleh' => Carbon::now()->setYear('2000')->format('Y-m-d H:i:s'), 'nomor_seri' => 'ADJK5102W'],
            ['id' => '689', 'jenis' => 'Laptop', 'merk' => 'HP', 'tipe' => 'Lainnya', 'tahun_peroleh' => Carbon::now()->setYear('2014')->format('Y-m-d H:i:s'), 'nomor_seri' => '5CD8327X7X'],
            ['id' => '690', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 3020 Micro', 'tahun_peroleh' => Carbon::now()->setYear('2016')->format('Y-m-d H:i:s'), 'nomor_seri' => 'tidak ada stiker'],
            ['id' => '691', 'jenis' => 'PC', 'merk' => 'HP', 'tipe' => 'Prodesk 41 G5 SFF', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => '1CZ83101QX'],
            ['id' => '692', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 3010 DT', 'tahun_peroleh' => Carbon::now()->setYear('2013')->format('Y-m-d H:i:s'), 'nomor_seri' => '5VB2G2S'],
            ['id' => '693', 'jenis' => 'Laptop', 'merk' => 'LENOVO', 'tipe' => 'V330', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => 'MP1DWKKW'],
            ['id' => '694', 'jenis' => 'Laptop', 'merk' => 'HP', 'tipe' => 'Lainnya', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => 'SCD8327X91'],
            ['id' => '695', 'jenis' => 'Headset/Earphone', 'merk' => 'Vivan', 'tipe' => 'Sport X True Wireless Stereo Earbuds', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => '30602118K'],
            ['id' => '697', 'jenis' => 'Laptop', 'merk' => 'ASUS', 'tipe' => 'VIVOBOOK 14', 'tahun_peroleh' => Carbon::now()->setYear('2019')->format('Y-m-d H:i:s'), 'nomor_seri' => 'L9L0CV21N92540C'],
            ['id' => '698', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'Optiplex 3040 Micro', 'tahun_peroleh' => Carbon::now()->setYear('2016')->format('Y-m-d H:i:s'), 'nomor_seri' => '3775086434'],
            ['id' => '699', 'jenis' => 'PC', 'merk' => 'ASUS', 'tipe' => 'Lainnya', 'tahun_peroleh' => Carbon::now()->setYear('2014')->format('Y-m-d H:i:s'), 'nomor_seri' => 'E9PTBX003480'],
            ['id' => '700', 'jenis' => 'PC', 'merk' => 'EPSON', 'tipe' => 'L6170', 'tahun_peroleh' => Carbon::now()->setYear('2020')->format('Y-m-d H:i:s'), 'nomor_seri' => 'X4EZ008456'],
            ['id' => '701', 'jenis' => 'PC', 'merk' => 'EPSON', 'tipe' => 'L15160', 'tahun_peroleh' => Carbon::now()->setYear('2021')->format('Y-m-d H:i:s'), 'nomor_seri' => 'X6MQ003583'],
            ['id' => '703', 'jenis' => 'Laptop', 'merk' => 'LENOVO', 'tipe' => 'V330', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => 'MP1DAV2E'],
            ['id' => '704', 'jenis' => 'Laptop', 'merk' => 'HP', 'tipe' => '440 G5', 'tahun_peroleh' => Carbon::now()->setYear('2018')->format('Y-m-d H:i:s'), 'nomor_seri' => '5CD8327X62'],
            ['id' => '705', 'jenis' => 'PC', 'merk' => 'DELL', 'tipe' => 'OPTIPLEX 780', 'tahun_peroleh' => Carbon::now()->setYear('2010')->format('Y-m-d H:i:s'), 'nomor_seri' => '81BHS2S'],


        ];
        MasterBarang::insert($data);
    }
}